Repository KallistiOS/kos-ports, pull requests merged in 2024-07, with the labels that each got.

#75 Upgraded Lua to latest version 5.4.7.
  lua/Makefile
  lua/distinfo
Labels: update

#72 Adjust mrbc install path in mrubyc port
  mruby/files/KOSMakefile.mk
Labels: enhancement

#74 Fix unsupported bash for MacOS
  utils/build-all.sh
Labels: build failure
