Repository KallistiOS/kos-ports, pull requests merged in 2025-08, with the labels that each got.

#116 build.mk script to use kos-cmake wrapper.
  scripts/build.mk
Labels: bug

#110 scripts: Support non-Makefile CMake generators
  scripts/build.mk
Labels: bug, build failure

#119 `libADX`: Bump to v1.0.1
  libADX/Makefile
Labels: update

#120 `mruby`: improvement on `rake` detection
  mruby/files/KOSMakefile.mk
Labels: build failure
